### ISSUE TITLE
Incompatible with latest photutils package

### ISSUE THREAD

**Issue by GillesOrban** [vortex-exoplanet/QACITS#2]
Photutils (since 2.0.0) now requires to import the subpackage name in the import. This means, e.g. 
`import photutils
aper = photutils.CircularAperture((10, 20), r=4)`

does not work anymore, and the following should be used:

`from photutils import aperture
aper = aperture.CircularAperture((10, 20), r=4) 
`

Should be easy to modify. More generally, the action would be to verify the functionality of the package with the latest versions of its dependencies (photutils, matplotlib, numpy, etc.). I can be assigned to it.

**Comment by GillesOrban** [comment]
@oabsil @ChrisDelaX would be useful if you could add me as 'collaborators' with 'admin' or 'maintain' rights.

**Comment by oabsil** [comment]
I've added you with admin rights. As far as I'm concerned, you can go ahead with the proposed modification(s).

**Comment by GillesOrban** [comment]
implemented and tested with `demo.ipynb`

**Comment by GillesOrban** [comment]
implemented and tested with demo.ipynb
